### PR TITLE
Create helm chart

### PR DESCRIPTION
**Pull request by hanzala1234**

### CODE REVIEW

**Comment by stakater-bot-lab** [comment]
Tekton - Pipeline ran successfully and image `docker.io/stakater/stakater-nordmart-inventory:SNAPSHOT-PR-29-ce75e3cb` is available

**Comment by stakater-bot-lab** [comment]
Tekton - Pipeline ran successfully and image `docker.io/stakater/stakater-nordmart-inventory:SNAPSHOT-PR-29-0f1c7f00` is available

**Comment by stakater-user** [comment]
Tekton - Pipeline ran successfully and image `nexus.openshift-stakater-nexus.svc.cluster.local:5003/repository/docker/stakater-nordmart-inventory:SNAPSHOT-PR-29-e67461aa` is available

**Comment by stakater-user** [comment]
Tekton - Pipeline ran successfully and image `nexus.openshift-stakater-nexus.svc.cluster.local:5003/repository/docker/stakater-nordmart-inventory:SNAPSHOT-PR-29-b0b2b987` is available

**Review by rasheedamir — APPROVED** [review]

**Pull request merged**
