### PR TITLE
Change configmap to secret

### PR DESCRIPTION
**Pull request by kahootali**

### CODE REVIEW

**Review by ahmedwaleedmalik — DISMISSED** [review]

**Comment by stakater-user** [comment]
Tekton - Pipeline ran successfully and image stakater/stakater-nordmart-inventory:$(IMAGE_TAG) is available

**Comment by stakater-user** [comment]
@kahootali Yikes! You better fix it before anyone else finds out! [Build 1](https://jenkins-delivery.stakater.com/job/nordmart-lab/job/stakater-nordmart-inventory/job/PR-23/1/) has Failed!

**Comment by stakater-user** [comment]
Tekton - Pipeline ran successfully and image stakater/stakater-nordmart-inventory:$(IMAGE_TAG) is available

**Comment by stakater-user** [comment]
@kahootali Image is available for testing. `docker pull docker-delivery.stakater.com:443/stakater-lab/inventory:0.0.0-PR-23-2-SNAPSHOT`

**Review by usamaahmadkhan — APPROVED** [review]

**Pull request merged**
