### PR TITLE
update-readme-doc

### PR DESCRIPTION
**Pull request by aliartiza75**
updated README.md doc

### CODE REVIEW

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker-release.workshop.stakater.com:443/stakater/inventory:SNAPSHOT-PR-4-1`

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker-release.workshop.stakater.com:443/stakater/inventory:SNAPSHOT-PR-4-2`

**Comment by hamza3202** [comment]
Replaced with https://github.com/stakater-lab/stakater-nordmart-inventory/pull/6

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker-release.workshop.stakater.com:443/stakater/inventory:SNAPSHOT-PR-4-3`

**Pull request closed without merging**
