### PR TITLE
fix helm values

### PR DESCRIPTION
**Pull request by rasheedamir**

### CODE REVIEW

**Comment by stakater-bot-lab** [comment]
Tekton - Pipeline ran successfully and image `docker.io/stakater/stakater-nordmart-inventory:SNAPSHOT-PR-28-8467c72c` is available

**Comment by stakater-bot-lab** [comment]
Tekton - Pipeline ran successfully and image `docker.io/stakater/stakater-nordmart-inventory:SNAPSHOT-PR-28-5796b622` is available

**Comment by stakater-bot-lab** [comment]
Tekton - Pipeline ran successfully and image `docker.io/stakater/stakater-nordmart-inventory:SNAPSHOT-PR-28-c3ca4be2` is available

**Comment by stakater-bot-lab** [comment]
Tekton - Pipeline ran successfully and image `docker.io/stakater/stakater-nordmart-inventory:SNAPSHOT-PR-28-c3ca4be2` is available

**Review by kahootali — APPROVED** [review]

**Pull request merged**
